### PR TITLE
create version v0.1

### PR DESCRIPTION
**Pull request by generationmake**
create initial release v0.1

### CODE REVIEW

**Comment by generationmake** [comment]
Hello @aentinger the schematic is now 95 % finished and all major parts are in it. could you please review it?
I plan to add a 32 kHz clock generator.
I think we should also add a common I2C connector like Qwiic. I would also like to add a connector for the second serial port.

**Comment by generationmake** [comment]
Hi @aentinger I finished the first placement and added some renderings. The USB connector and the display connector are still the wrong footprints. But I think you can imagine what it will look alike. The battery holders are now the highest parts with 4 mm and there are no parts on the bottom side. So the whole device will be very slim.

I added the ATECC608 because it is small and has only a few connections. I don't know yet how we can use it. Maybe for signing NFC VCards or authentication via NFC.
I used the CP2102 because I already had it in my library and it worked fine in previous projects. I will change it to the FTDI part

design proposal:
Maybe we can add some accelerometer sensor. So the device could be used as a step counter.

**Comment by aentinger** [comment]
Good morning @generationmake :wave: great work! A bit of feedback from my side:
* We can leave the ATECC608 and just not populate the relevant parts on the board if we don't find a handy use-case in the end.
* Let's replace the CP2102 with the FT232 then because the latter one definitely works on all operating systems without requiring any driver installation.
* We can add an accelerometer which we may or may not choose to populate later during manufacturing. I'd like to focus on the pure business card application for now. When selecting an accelerometer, please make sure they already come with builtin step-detection algorithm (it's a rather common feature in modern MEMS accs/imus)
* I want to pick up on your suggestion concerning expansion connectors: Please lets definitely add a Qwiic connectors for I2C and one for the other UART. Is there kind-of a connector standard for UART as there is the Qwiic for I2C?
* I've got another question concerning the display: I don't see mechanical mounting points except the connector. How will the display stay securely attached to the board even if the whole thing is manhandled somewhat.
* I'd also like to mention design for testability - Can you add test-points at interesting spots (I2C bus, SPI bus, output of voltage regulators) so that the bring-up phase is made easier as well with an eye towards automatic testing at the manufacturer?

**Comment by generationmake** [comment]
Hi @aentinger 
I switched the USB controller to FT230X ( https://www.ftdichip.com/Products/ICs/FT230X.html ).I hope this one is OK. It is a little bit smaller and much cheaper than FT232RL.
For I2C I added a Qwiic connector: https://www.sparkfun.com/qwiic
For UART I added a grove connector: https://wiki.seeedstudio.com/Grove_System/

Accelerometer will follow. I am thinking of using a Bosch Sensortec BMA400 ( https://www.bosch-sensortec.com/products/motion-sensors/accelerometers/bma400.html ).

At the moment there are still some overlapping parts in the placement. I will fix this when the schematic and BOM is finished but I think you can see that all parts fit on the board and that the rough position is fixed.

I will add test points to the bottom side of the PCB which is now completely empty.

**Comment by aentinger** [comment]
Hi @generationmake :wave:
That's great! :+1: :rocket: You are working so fast that I've got a hard time to keep up with you ;) There were a couple of more ideas I wanted to run by you:
* Currently the reset and wake button are of the same type as the user interface buttons. I believe they should be made different and hard to reach in order to prevent accidental triggering of those buttons. Therefore I was thinking of using a [different type of button](https://at.farnell.com/panasonic/evqp46b3m/taster-spst-0-02a-15v-kartenrandmontage/dp/2831748) which is mounted to the side of the PCB for reset/wake.
* Another thing which has a similar idea: In order to avoid accidental triggering of the user buttons I'd like add like a mechanical keylock switch which needs to be engaged first - otherwise the user buttons won't work. I was thinking of either a sliding switch similar to power or (more to my preference) a "[Kippschalter](https://at.farnell.com/c-k-components/et01md1sape/kippschalter-spdt-0-4va-20v/dp/2435141)". What do you think?
* Also one question I'm not clear on yet: wow much of the PCB is currently covered by the display?

**Comment by generationmake** [comment]
@aentinger You are right with the reset button. I will use a different style of button which can't be pressed accidently.
But can you check again on the wake button. I know this pin has the wake function. But what about when the system is already alive? Can this pin be used as a normal input?

I am not OK with the sliding switch (Kippschalter) as keylock because this adds more signals and components. I think we should do this in software. And we are also already running out of pins on the micro controller.

I will add a 3D image of the pcb with display tonight.

**Comment by aentinger** [comment]
I've checked the wake button again. This button can be used to wake the processor from deep sleep but can not be used as general purpose input. Therefore we can actually leave it to the same type of button as the user interface.
I see that we are already quite space constrained ... let's do the keylock in software then.

**Comment by generationmake** [comment]
@aentinger I added a rendering of the business card with display.

**Comment by aentinger** [comment]
Good morning :wave:
* The rendering including the display looks great. I'm slightly concerned about the stability of the display but if you believe you can handle it with a 3D printed frame then so be it.
* Can you please export the schematic to PDF again, I could not find the BMA400 on it.
* From the 3D-Rendering as well as the TOP PCB view I get the idea that C18 and C1 are overlapping with one another and both are also reaching well into the BT1 battery holder. I'm afraid of the battery directly touching those components. Can you confirm or dispell?

**Comment by generationmake** [comment]
Good morning,
I have no fear of cracking the display. The PCB gives enough stability against bending. We just have to ensure that the display stays in a defined distance of the PCB. And this does the 3D printed frame.
Alternatively we could switch to a smaller display as most e-paper displays have the same connector and pin out. like this one: https://www.waveshare.com/wiki/1.54inch_e-Paper_Module_(B)

Don't mind of the placement issues. I will fix them when schematic and BOM is finished.

I suggest also to move the JTAG connector to the edge of the board so that you can connect when the display is in place. I would like to use this one: https://www.samtec.com/products/fsh ( FSH-105-04-L-DH ). Do you think there is a problem when the JTAG traces are slightly longer?

I will update the shematic tonight and also try to finisch the placement.

**Comment by aentinger** [comment]
Good morning @generationmake :wave:
* I think it would be best to have the display as large as possible. We will get a real feeling once we handle the actual prototype so let's wait for that one.
* Your linked JTAG-Connector looks good to me, it should work out with the female connectors I've got on the Segger JLink.

**Comment by generationmake** [comment]
@aentinger I'm doing now review regarding BOM costs.

It seems like all Bosch BMA accelerometers have the same footprint and pinout. So I suggest to use the cheapest available part. This is IMHO the BMA256:
https://www.bosch-sensortec.com/products/motion-sensors/accelerometers/bma253.html
https://www.digikey.de/product-detail/de/bosch-sensortec/BMA253/828-1071-1-ND/7164923
Is this one OK for you?

**Comment by aentinger** [comment]
Good Morning :wave: I've checked the datasheet and it seems to have all the relevant features (and more). If I've got some spare time (haha) I'll go and have a look what's the difference between all those parts. They seem similar enough on first glance.

**Comment by generationmake** [comment]
@aentinger I updated the BOM and schematic.

Do you have any instructions how to connect the interrupt line of the BMA253 to the microcontroller?
With a diode on WAKE#?

**Comment by aentinger** [comment]
Good Morning :wave: Both INT1 and INT2 can be configured as open-drain output type, therefore a simple trace to the wake pin should suffice (page 73 in the datasheet). What do you think about that?

**Comment by generationmake** [comment]
Hi @aentinger schematic and layout could be finished. Can you review them?

Do you have any suggestions what to put on the silkscreen?

**Comment by aentinger** [comment]
Good Morning @generationmake :wave:

Good work 👍 I've been thoroughly reviewing the schematic. Here's what I've come up with:

* There seem to be wrong labels on the power circuit for the wave share display (although the wiring itself seems to be correct). The circuit shown on page 32 of the [datasheet](https://www.waveshare.com/w/upload/b/bb/2.9inch-e-paper-b-specification.pdf) shows that what in our schematic is called `VGL` is really called `PREVGL` and `VGH` is really called `PREVGH`. This is a bit confusing as there are really `VGL` and `VGH` pin which are allocated on pins 4 and 5 of the connector. According to the sample schematic on page 31 these pins should be connected to GND via a 1 µF condensator (which is missing for pin 4 / `VGL`).
* I assume you use the `SSOP` package of the `FT230XS` chip? The QFN package has different pin assignments.
* I believe there is an incorrect assignment of the UART pins to the FT230XS. UART0 pins on the FE310 are `16: UART0_RX` and `17:  UART0_TX`. So right now its 
  * `FE310 UART0 RX / 16` -> `FT230XS RXD / 4`
  * `FE310 UART0 TX / 17` -> `FT230XS TXD / 1`
which I believe is wrong. Can you please confirm my finding?
* What is the default output of `FT230XS RTS# / 1`? I couldn't find it in the datasheet. If it's high, then we are pulling the reset low.
* Suggestion: Add a high value resistor (1 M?) pulling `RTS_R` towards `GND` to safely disable reset by FT230XS during startup (not sure if it's really necessary, it really depends on the behaviour of the `FT230XS RTS#` pin).

Here's a list of items I checked:
* MicroSD card ✔️ 
* JTAG ✔️ 
* Qwiic ✔️ 
* BMA253 ✔️ 
* W25Q80D ✔️ 
* W25Q80D ✔️ 
* ATECC608A ✔️ 
* M24LR ✔️ 
* FT230XS ✔️
* FE310 (special IO functions to gpio mapping) ✔️

**Comment by generationmake** [comment]
Good morning @aentinger 
Thank you for your review.

I think I used a different type and datasheet for the display: https://www.unisystem-displays.com/en/products/epd/use0290-bwnl-01.html
I thought all epaper displays are the same but now it seems they are not. I will check if I can make them compatible.

Yes, the FT230X is in the SSOP package. 

The RTS pin is an output and high when inactive. So it would really keep the microcontroller in reset. I will rework this circuit. During reset of the FT230X this pin is tri-stated with a week pull up to VCCIO (75k).

ANd yes, rx and tx are swapped ....

I will fix all issues.

**Comment by generationmake** [comment]
Hi @aentinger 
I think I fixed all issues and updated the silk screen. From my side I am finished. Please review again. 
And provide any images and texts you want on the silk screen.

**Comment by generationmake** [comment]
Hi @aentinger 
I think I added all necessary documentation. Or is something missing?
If not, please merge with master.

**Pull request merged**
