### PR TITLE
Display holder

### PR DESCRIPTION
**Pull request by generationmake**
This branch should contain all additional mechanical parts necessary to build the complete business card.

### CODE REVIEW

**Comment by aentinger** [comment]
Wow, this looks fantastic :rocket: Great work @generationmake! Is this branch ready to merge?

**Comment by generationmake** [comment]
Hi @aentinger 
I printed the first prototype of the display holder and it turned out that there are some collisions. I will redesign the part and test again.

**Comment by generationmake** [comment]
I printed and tested the new design and it fits perfectly.
@aentinger could you please review this branch and merge with master.

**Review by aentinger — APPROVED** [review]
Looking great :100: Thank you very much @generationmake :rocket:

**Pull request merged**
